# Site settings

title: The game journal
description: It is minimal and lazy!
logo: ./imgs/space-invaders-svgrepo-com.svg

email: nikhri98@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: ""
github_username: nikolahristov98

future: true
markdown: kramdown

plugins:
  - jekyll-feed

destination: "docs"

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - gulpfile.js
  - docs
  - node_modules
  - scss